[package]
name = "allocators"
version = "0.1.0"
authors = ["Steffen Haug <steffenandr@gmail.com>"]

[dependencies]


[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "alloc_bench"
harness = false

[[bin]]
name = "executable"
path = "src/main.rs"

[lib]
name = "allocators"
path = "src/lib.rs"
